package com.chatbrain.events;

public enum EventType {
	CHAT_MESSAGE,
	SUBSCRIBER,
	MEMBER_JOINED,
	USER_RESOLVED,
	BUILD_SUCCEEDED,
	COMPILATION_FAILED,
	APPLICATION_STARTED,
	FEATURE_COMPLETED,
	LONG_DEBUG_SESSION,
	LONG_SILENCE,
	MILESTONE_REACHED
}
