package com.chatbrain.comedy;

public enum ComedyStyle {
	NO_HUMOR,
	DEVELOPER_HUMOR,
	DRY_SARCASM,
	OBSERVATIONAL_HUMOR,
	ANALOGY_HUMOR,
	FRIENDLY_ROAST,
	SELF_ROAST,
	CALLBACK_HUMOR,
	CELEBRATION_HUMOR,
	TEACHING_THROUGH_HUMOR,
	INDIAN_ENGINEERING_CULTURE,
	INDIAN_OFFICE_CULTURE,
	STARTUP_CULTURE,
	ENGINEERING_COLLEGE_NOSTALGIA,
	BOLLYWOOD_ANALOGY,
	CRICKET_ANALOGY,
	TECH_TWITTER_HUMOR,
	INTERNET_MEME_REFERENCE
}
