package com.chatbrain.comedy;

public enum ComedyOpportunity {
	NONE,
	SERIOUS_TECHNICAL,
	TECHNICAL_QUESTION,
	DOCKER_FAILURE,
	COMPILATION_ERROR,
	LONG_DEBUGGING,
	DEPENDENCY_HELL,
	SPRING_RESTART,
	BUILD_FAILURE,
	CONFIGURATION_ERROR,
	OVERENGINEERING,
	FEATURE_CREEP,
	MERGE_CONFLICT,
	VIEWER_TROLLING,
	FRIENDLY_ROAST,
	MILESTONE,
	SUCCESS,
	LATE_NIGHT_CODING,
	COFFEE,
	INDIAN_ENGINEERING_CONTEXT,
	INDIAN_OFFICE_CONTEXT,
	STARTUP_CONTEXT,
	BOLLYWOOD_CONTEXT,
	CRICKET_CONTEXT
}
